# Generated by Django 2.0.8 on 2022-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileID', models.CharField(max_length=100)),
                ('filename', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
