# Generated by Django 2.0.8 on 2019-03-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileID', models.IntegerField(db_index=True)),
                ('filename', models.CharField(db_index=True, max_length=25)),
            ],
        ),
    ]
