# Generated by Django 2.0.8 on 2019-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal_db',
            name='fileID',
            field=models.CharField(max_length=50),
        ),
    ]
