# Generated by Django 2.0.8 on 2019-03-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgclass', '0002_auto_20190307_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal_db_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=5)),
                ('filename', models.CharField(db_index=True, max_length=25)),
                ('value', models.FloatField()),
            ],
        ),
    ]
