# Generated by Django 2.0.8 on 2019-03-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgclass', '0003_signal_db_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal_db_info',
            name='filename',
        ),
        migrations.AddField(
            model_name='signal_db_info',
            name='fileID',
            field=models.CharField(db_index=True, default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
