# Generated by Django 2.0.8 on 2019-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgclass', '0004_auto_20190318_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal_db',
            name='fileID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signal_db',
            name='filename',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
