# Generated by Django 2.0.8 on 2019-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal_mmTen_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileID', models.CharField(max_length=50)),
                ('filename', models.CharField(db_index=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Signal_mmTen_db_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=5)),
                ('value', models.FloatField()),
                ('fileID', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
