# Generated by Django 2.0.8 on 2019-03-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgclassMMTen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signal_mmTen_db',
        ),
    ]
